"""Base interface for perspective-specific analysis.

A perspective represents a disciplinary lens through which place names
can be analysed (linguistics, geography, archaeology, etc.). Each
perspective module knows how to:
1. Extract relevant features for a place
2. Generate testable hypotheses from its domain
3. Interpret results in its disciplinary context
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any
from uuid import UUID


@dataclass
class Hypothesis:
    """A testable hypothesis generated by a perspective."""

    claim: str
    null_hypothesis: str
    test_family: str
    parameters: dict[str, Any] = field(default_factory=dict)
    preregistered: bool = False
    source: str = ""  # Which perspective generated this


class BasePerspective(ABC):
    """Abstract base class for perspective-specific analysis modules.

    To add a new perspective:
    1. Create a module in src/toponymia/perspectives/
    2. Subclass BasePerspective
    3. Implement extract_features() and generate_hypotheses()
    4. Define the required data sources
    """

    # Class-level metadata (override in subclass)
    perspective_id: str = ""
    name: str = ""
    description: str = ""
    required_data: list[str] = []  # Data layers needed for this perspective

    @abstractmethod
    def extract_features(self, place_id: UUID) -> dict[str, Any]:
        """Extract features relevant to this perspective for a place.

        Args:
            place_id: UUID of the place to analyse.

        Returns:
            Dict of feature_name -> value pairs.
        """
        ...

    @abstractmethod
    def generate_hypotheses(self, place_id: UUID) -> list[Hypothesis]:
        """Generate testable hypotheses from this perspective.

        Args:
            place_id: UUID of the place to generate hypotheses for.

        Returns:
            List of testable Hypothesis objects.
        """
        ...

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} id={self.perspective_id!r}>"
